### PR TITLE
Fix depth alpha

### LINKED ISSUE #315: DepthGaussianNoise integration test fails on some HW
I noticed DepthGaussianNoise fails on my machine but works fine in the CI server.

The integration fails:

```
[ RUN      ] GaussianNoise/RenderPassTest.DepthGaussianNoise/ogre2
/home/matias/Projects/ign/src/ign-rendering/test/integration/render_pass.cc:357: Failure
Expected equality of these values:
  255u
    Which is: 255
  ma
    Which is: 0
[  FAILED  ] GaussianNoise/RenderPassTest.DepthGaussianNoise/ogre2, where GetParam() = "ogre2" (12204 ms)
```

To be more specific the integration expects an alpha value (packed/encoded) of 255, but instead it's 0.

Upon closer examination, this is because the test uploads this colour texture:

colourTexture

However the texture is of format R8G8B8_SRGB, therefore GPUs are allowed to do whatever they want with the alpha value.

In the case of my AMD Radeon RX 560 2GB using Mesa drivers, it decides to fetch an alpha of 0 instead of 255, thus causing the test to fail.

This bug should fix itself in the Ogre 2.2 version, because Ogre 2.2 explicitly forbids the use of RGB888 textures in the GPU. The `PFG_RGB8_*` family of pixel formats can only be used for CPU operations.

## Environment
* OS Version: Xubuntu 18.04 LTS
* Source or binary build? https://github.com/ignitionrobotics/ign-rendering/commit/07c4ca96c924db4004ccab9e0b7a1e6ac5b1b033
    - Rendering plugin: ogre2
      - [x] running on real hardware
    - Rendering system info:
```
direct rendering: Yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon RX 560 Series (POLARIS11, DRM 3.40.0, 5.11.0-051100-generic, LLVM 10.0.1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.1.3 (git-663fa46287)
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.1.3 (git-663fa46287)
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.1.3 (git-663fa46287)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

08:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon RX 550 640SP / RX 560/560X] [1002:67ff] (rev cf)

root      1680  1.4  0.5 2840064 165080 tty7   Ssl+ 18:35   0:27 /usr/lib/xorg/Xorg -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
matias   11249  0.0  0.0  17988  1032 pts/2    S+   19:05   0:00 grep --color=auto Xorg
 ```

## Description

* Expected behavior: Test should pass
* Actual behavior: Test fails

## Steps to reproduce

1. Run ign/build/ignition-rendering5/bin/INTEGRATION_render_pass
2. Use AMD Radeon RX 560 2GB HW, Mesa drivers.

## Workaround

Run the test with LIBGL_ALWAYS_SOFTWARE=1

## Other

This bug is incredibly low priority for me; given that the CI does its job, I can comment out the failing lines involving alpha or workaround it with SW, and that it should fix itself with Ogre 2.2

### PR DESCRIPTION
**Pull request by iche033**
# 🦟 Bug fix

Fixes #315 

## Summary

Fixes tests that check the alpha value of pixels returned by the Depth Camera. As explained in #315, the internal texture format does not have an alpha channel so the graphics card driver is free to fill any value it wants. I've updated the test to check for either `255` or `0` which we have seen on the CI machines and also on a computer with AMD card with mesa driver. I'm also open to just removing this check in the test.

I also re-enabled the test on macOS :crossed_fingers: 

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

File: test/integration/depth_camera.cc [hunk 1]
```diff
@@ -280,7 +278,16 @@ void DepthCameraTest::DepthCameraBoxes(
       EXPECT_EQ(255u, rr);
       EXPECT_EQ(0u, rg);
       EXPECT_EQ(0u, rb);
-      EXPECT_EQ(255u, ra);
+
+      // Note: internal texture format used is RGB with no alpha channel
+      // We observed the values can be either 255 or 0 but graphics card
+      // drivers are free to fill it with any value they want.
+      // This should be fixed in ogre 2.2 in ign-rendering6 which forbids
+      // forbids the use of RGB format.
```
Comment (chapulina) [inline test/integration/depth_camera.cc:286]:
```suggestion
      // the use of RGB format.
```

File: test/integration/render_pass.cc [hunk 2]
```diff
@@ -379,7 +377,16 @@ void RenderPassTest::DepthGaussianNoise(const std::string &_renderEngine)
       EXPECT_NEAR(255u, rr, colorNoiseTol);
       EXPECT_NEAR(0u, rg, colorNoiseTol);
       EXPECT_NEAR(0u, rb, colorNoiseTol);
-      EXPECT_EQ(255u, ra);
+
+      // Note: internal texture format used is RGB with no alpha channel
+      // We observed the values can be either 255 or 0 but graphics card
+      // drivers are free to fill it with any value they want.
+      // This should be fixed in ogre 2.2 in ign-rendering6 which forbids
+      // forbids the use of RGB format.
```
Comment (chapulina) [inline test/integration/render_pass.cc:385]:
```suggestion
      // the use of RGB format.
```

**Review by chapulina — COMMENTED** [review]
:crossed_fingers: :apple:

File: test/integration/render_pass.cc (hunk 2 above)
Comment (iche033) [reply test/integration/render_pass.cc]: 5edb5cd6b2344d6de663f3278727025cac6648e0

File: test/integration/depth_camera.cc (hunk 1 above)
Comment (iche033) [reply test/integration/depth_camera.cc]: 5edb5cd6b2344d6de663f3278727025cac6648e0

**Review by chapulina — APPROVED** [review]
All tests passed on macOS on the latest run! :smile:

**Comment by iche033** [comment]
alright, I think CI ran twice and both times the homebrew build passed. Merging!
